# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github:
        patterns:
          - "actions/*"
          - "github/*"
    schedule:
      interval: "weekly"
