# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/platform/shared/v1alpha1/pagination.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9agntcy/identity/platform/shared/v1alpha1/pagination.proto\x12(agntcy.identity.platform.shared.v1alpha1\"\xa4\x01\n\rPagedResponse\x12 \n\tnext_page\x18\x01 \x01(\x05H\x00R\x08nextPage\x88\x01\x01\x12\'\n\rhas_next_page\x18\x02 \x01(\x08H\x01R\x0bhasNextPage\x88\x01\x01\x12\x14\n\x05total\x18\x03 \x01(\x03R\x05total\x12\x12\n\x04size\x18\x04 \x01(\x05R\x04sizeB\x0c\n\n_next_pageB\x10\n\x0e_has_next_pageB\xfd\x02\n,com.agntcy.identity.platform.shared.v1alpha1B\x0fPaginationProtoP\x01Zwgithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/shared/v1alpha1;identity_platform_shared_sdk_go\xa2\x02\x04\x41IPS\xaa\x02(Agntcy.Identity.Platform.Shared.V1alpha1\xca\x02(Agntcy\\Identity\\Platform\\Shared\\V1alpha1\xe2\x02\x34\x41gntcy\\Identity\\Platform\\Shared\\V1alpha1\\GPBMetadata\xea\x02,Agntcy::Identity::Platform::Shared::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.platform.shared.v1alpha1.pagination_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.agntcy.identity.platform.shared.v1alpha1B\017PaginationProtoP\001Zwgithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/shared/v1alpha1;identity_platform_shared_sdk_go\242\002\004AIPS\252\002(Agntcy.Identity.Platform.Shared.V1alpha1\312\002(Agntcy\\Identity\\Platform\\Shared\\V1alpha1\342\0024Agntcy\\Identity\\Platform\\Shared\\V1alpha1\\GPBMetadata\352\002,Agntcy::Identity::Platform::Shared::V1alpha1'
  _globals['_PAGEDRESPONSE']._serialized_start=104
  _globals['_PAGEDRESPONSE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
