# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

---
extends: default

rules:
  line-length:
    max: 500
    level: warning
  comments: disable
  indentation: disable
  truthy:
    check-keys: false
