# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
extends: default

rules:
  line-length:
    max: 500
    level: warning
  comments: disable
  indentation: disable
  truthy:
    check-keys: false
