# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/platform/v1alpha1/openapi.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openapiv3 import annotations_pb2 as openapiv3_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/agntcy/identity/platform/v1alpha1/openapi.proto\x12!agntcy.identity.platform.v1alpha1\x1a\x1bopenapiv3/annotations.protoB\x9a\x06\n%com.agntcy.identity.platform.v1alpha1B\x0cOpenapiProtoP\x01Zigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_go\xa2\x02\x03\x41IP\xaa\x02!Agntcy.Identity.Platform.V1alpha1\xca\x02!Agntcy\\Identity\\Platform\\V1alpha1\xe2\x02-Agntcy\\Identity\\Platform\\V1alpha1\\GPBMetadata\xea\x02$Agntcy::Identity::Platform::V1alpha1\xbaG\xcf\x03\x12\xdc\x01\n\x12\x41gent Identity API\x12tAgent Identity API provides a set of endpoints for managing identity and access control within the AGNTCY ecosystem.\"F\n\x0b\x41GNTCY Team\x12\"https://github.com/agntcy/identity\x1a\x13identity@agntcy.org2\x08v1alpha1\x1a*\n\x15http://localhost:4000\x12\x11Local environment*\xa2\x01\x32\x02\n\x00:\x9b\x01\n\\\n\x0b\x41\x63\x63\x65ssToken\x12M\nK\n\x04http\x12\x36\x41n IAM JWT token issued to a user during an OIDC flow.*\x06\x62\x65\x61rer2\x03JWT\n;\n\x06\x41piKey\x12\x31\n/\n\x06\x61piKey\x12\x0f\x41n IAM Api key.\x1a\x0cx-id-api-key\"\x06header2\x1d\n\x0f\n\x0b\x41\x63\x63\x65ssToken\x12\x00\n\n\n\x06\x41piKey\x12\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.platform.v1alpha1.openapi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.agntcy.identity.platform.v1alpha1B\014OpenapiProtoP\001Zigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_go\242\002\003AIP\252\002!Agntcy.Identity.Platform.V1alpha1\312\002!Agntcy\\Identity\\Platform\\V1alpha1\342\002-Agntcy\\Identity\\Platform\\V1alpha1\\GPBMetadata\352\002$Agntcy::Identity::Platform::V1alpha1\272G\317\003\022\334\001\n\022Agent Identity API\022tAgent Identity API provides a set of endpoints for managing identity and access control within the AGNTCY ecosystem.\"F\n\013AGNTCY Team\022\"https://github.com/agntcy/identity\032\023identity@agntcy.org2\010v1alpha1\032*\n\025http://localhost:4000\022\021Local environment*\242\0012\002\n\000:\233\001\n\\\n\013AccessToken\022M\nK\n\004http\0226An IAM JWT token issued to a user during an OIDC flow.*\006bearer2\003JWT\n;\n\006ApiKey\0221\n/\n\006apiKey\022\017An IAM Api key.\032\014x-id-api-key\"\006header2\035\n\017\n\013AccessToken\022\000\n\n\n\006ApiKey\022\000'
# @@protoc_insertion_point(module_scope)
