# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/platform/v1alpha1/settings_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agntcy.identity.platform.v1alpha1 import settings_pb2 as agntcy_dot_identity_dot_platform_dot_v1alpha1_dot_settings__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8agntcy/identity/platform/v1alpha1/settings_service.proto\x12!agntcy.identity.platform.v1alpha1\x1a\x30\x61gntcy/identity/platform/v1alpha1/settings.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x14\n\x12GetSettingsRequest\"\x12\n\x10SetApiKeyRequest\"s\n\x10SetIssuerRequest\x12_\n\x0fissuer_settings\x18\x01 \x01(\x0b\x32\x31.agntcy.identity.platform.v1alpha1.IssuerSettingsB\x03\xe0\x41\x02R\x0eissuerSettings2\xbb\x05\n\x0fSettingsService\x12\xbb\x01\n\x0bGetSettings\x12\x35.agntcy.identity.platform.v1alpha1.GetSettingsRequest\x1a+.agntcy.identity.platform.v1alpha1.Settings\"H\x92\x41+\x12\x1bGet Settings for the Tenant*\x0cGet Settings\x82\xd3\xe4\x93\x02\x14\x12\x12/v1alpha1/settings\x12\xe4\x01\n\tSetApiKey\x12\x33.agntcy.identity.platform.v1alpha1.SetApiKeyRequest\x1a).agntcy.identity.platform.v1alpha1.ApiKey\"w\x92\x41R\x12\x0eSet up API Key\x1a@Create a new API Key for the Tenant. Revoke any previous API Key\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1alpha1/settings/api-key\x12\xf3\x01\n\tSetIssuer\x12\x33.agntcy.identity.platform.v1alpha1.SetIssuerRequest\x1a\x31.agntcy.identity.platform.v1alpha1.IssuerSettings\"~\x92\x41W\x12\x46\x43reate and register Issuer for the Tenant. Revoke any previous Issuer.*\rSet up Issuer\x82\xd3\xe4\x93\x02\x1e\"\x19/v1alpha1/settings/issuer:\x01*\x1a\r\x92\x41\n\n\x08SettingsB\xcf\x02\n%com.agntcy.identity.platform.v1alpha1B\x14SettingsServiceProtoP\x01Zigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_go\xa2\x02\x03\x41IP\xaa\x02!Agntcy.Identity.Platform.V1alpha1\xca\x02!Agntcy\\Identity\\Platform\\V1alpha1\xe2\x02-Agntcy\\Identity\\Platform\\V1alpha1\\GPBMetadata\xea\x02$Agntcy::Identity::Platform::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.platform.v1alpha1.settings_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.agntcy.identity.platform.v1alpha1B\024SettingsServiceProtoP\001Zigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_go\242\002\003AIP\252\002!Agntcy.Identity.Platform.V1alpha1\312\002!Agntcy\\Identity\\Platform\\V1alpha1\342\002-Agntcy\\Identity\\Platform\\V1alpha1\\GPBMetadata\352\002$Agntcy::Identity::Platform::V1alpha1'
  _globals['_SETISSUERREQUEST'].fields_by_name['issuer_settings']._options = None
  _globals['_SETISSUERREQUEST'].fields_by_name['issuer_settings']._serialized_options = b'\340A\002'
  _globals['_SETTINGSSERVICE']._options = None
  _globals['_SETTINGSSERVICE']._serialized_options = b'\222A\n\n\010Settings'
  _globals['_SETTINGSSERVICE'].methods_by_name['GetSettings']._options = None
  _globals['_SETTINGSSERVICE'].methods_by_name['GetSettings']._serialized_options = b'\222A+\022\033Get Settings for the Tenant*\014Get Settings\202\323\344\223\002\024\022\022/v1alpha1/settings'
  _globals['_SETTINGSSERVICE'].methods_by_name['SetApiKey']._options = None
  _globals['_SETTINGSSERVICE'].methods_by_name['SetApiKey']._serialized_options = b'\222AR\022\016Set up API Key\032@Create a new API Key for the Tenant. Revoke any previous API Key\202\323\344\223\002\034\"\032/v1alpha1/settings/api-key'
  _globals['_SETTINGSSERVICE'].methods_by_name['SetIssuer']._options = None
  _globals['_SETTINGSSERVICE'].methods_by_name['SetIssuer']._serialized_options = b'\222AW\022FCreate and register Issuer for the Tenant. Revoke any previous Issuer.*\rSet up Issuer\202\323\344\223\002\036\"\031/v1alpha1/settings/issuer:\001*'
  _globals['_GETSETTINGSREQUEST']._serialized_start=256
  _globals['_GETSETTINGSREQUEST']._serialized_end=276
  _globals['_SETAPIKEYREQUEST']._serialized_start=278
  _globals['_SETAPIKEYREQUEST']._serialized_end=296
  _globals['_SETISSUERREQUEST']._serialized_start=298
  _globals['_SETISSUERREQUEST']._serialized_end=413
  _globals['_SETTINGSSERVICE']._serialized_start=416
  _globals['_SETTINGSSERVICE']._serialized_end=1115
# @@protoc_insertion_point(module_scope)
